'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MK8A.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FontAwesome() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property miiverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miiverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__3DS_DK_Jungle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__3DS_DK_Jungle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__3DS_Music_Park() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__3DS_Music_Park", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__3DS_Piranha_Plant_Slide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__3DS_Piranha_Plant_Slide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Bone_Dry_Dunes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Bone_Dry_Dunes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Bowser_s_Castle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Bowser_s_Castle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Cloudtop_Cruise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Cloudtop_Cruise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Dolphin_Shoals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Dolphin_Shoals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__DS_Cheep_Cheep_Beach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__DS_Cheep_Cheep_Beach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__DS_Tick_Tock_Clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__DS_Tick_Tock_Clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__DS_Wario_Stadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__DS_Wario_Stadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Electrodrome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Electrodrome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__GBA_Mario_Circuit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__GBA_Mario_Circuit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__GCN_Dry_Dry_Desert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__GCN_Dry_Dry_Desert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__GCN_Sherbet_Land() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__GCN_Sherbet_Land", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Mario_Circuit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Mario_Circuit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Mario_Kart_Stadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Mario_Kart_Stadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Mount_Wario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Mount_Wario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__N64_Rainbow_Road() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__N64_Rainbow_Road", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__N64_Royal_Raceway() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__N64_Royal_Raceway", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__N64_Toad_s_Turnpike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__N64_Toad_s_Turnpike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__N64_Yoshi_Valley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__N64_Yoshi_Valley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Rainbow_Road() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Rainbow_Road", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Shy_Guy_Falls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Shy_Guy_Falls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__SNES_Donut_Plains_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__SNES_Donut_Plains_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Sunshine_Airport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Sunshine_Airport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Sweet_Sweet_Canyon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Sweet_Sweet_Canyon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Thwomp_Ruins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Thwomp_Ruins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Toad_Harbor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Toad_Harbor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Twisted_Mansion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Twisted_Mansion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Water_Park() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Water_Park", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Wii_Grumble_Volcano() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Wii_Grumble_Volcano", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MK8__Wii_Moo_Moo_Meadows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MK8__Wii_Moo_Moo_Meadows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
